import jsonp from 'common/js/jsonp'
import {commonParams, options} from './config'

export function getRecommend() {
  const url = 'https://c.y.qq.com/musichall/fcgi-bin/fcg_yqqhomepagerecommend.fcg'

  const data = Object.assign({}, commonParams, {
    platform: 'h5',
    uin: 0,
    needNewCode: 1
  })

  return jsonp(url, data, options)
}

export function getDiscList() {
  return {
    "code":0,
    "subcode":0,
    "message":"",
    "default":0,
    "data":{
      "uin":0,
      "categoryId":10000000,
      "sortId":5,
      "sum":5889,
      "sin":0,
      "ein":29,
      "list":[
        {
          "dissid":"1763974895",
          "createtime":"2017-05-24",
          "commit_time":"2017-05-24",
          "dissname":"美国电影协会评选100首电影金曲",
          "imgurl":"http://p.qpic.cn/music_cover/fnBKJkkMMr5DoiadmlXsCV7TJK8iafOYU9AibxFXKic86APSJmyf3iakrBg/600?n=1",
          "introduction":"",
          "listennum":158483,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2746186693,
            "encrypt_uin":"owSP7w6F7wCqoz**",
            "name":"灵儿响叮当",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"1480166274",
          "createtime":"2017-09-04",
          "commit_time":"2017-09-04",
          "dissname":"直击心灵的灵魂乐：70位歌手代表作",
          "imgurl":"http://p.qpic.cn/music_cover/5Olm9QQMvPcH2ZbO9nA2zGvRECehwFqHnvBZkicOGbmumpibk7GeiaJbA/600?n=1",
          "introduction":"",
          "listennum":281236,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2180497102,
            "encrypt_uin":"ow6Foevq7i6zoc**",
            "name":"我的歌单就是这么好",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3761252099",
          "createtime":"2018-03-06",
          "commit_time":"2018-03-06",
          "dissname":"钢琴家们指尖上的李斯特",
          "imgurl":"http://p.qpic.cn/music_cover/gSWEnBJhkxO1raoO4qZgwa3OQh0erWt82XBxUFx1PnoQCncAoGwWqg/600?n=1",
          "introduction":"",
          "listennum":14800,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2283027833,
            "encrypt_uin":"ow-FoinA7icioz**",
            "name":"野蔷薇",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3756831941",
          "createtime":"2018-03-02",
          "commit_time":"2018-03-02",
          "dissname":"传统器乐：丝竹谱响的江南风光",
          "imgurl":"http://p.qpic.cn/music_cover/ia1BhHY0pBXp25tpaaiaCzRemUbTt2GLgb8bm4dcbEYzRJL8Il1qh7Gg/600?n=1",
          "introduction":"",
          "listennum":15699,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":3043667928,
            "encrypt_uin":"oinPoiCs7iEANn**",
            "name":"。。。",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3780825131",
          "createtime":"2018-03-15",
          "commit_time":"2018-03-15",
          "dissname":"远山长慕，寒鸦声渡 • 慕寒原创",
          "imgurl":"http://p.qpic.cn/music_cover/NaYDCjF6oFDyCBFMbYpoK5w85FGBTyzt2cOVVraXOBU2ia2wEeyAsFw/600?n=1",
          "introduction":"",
          "listennum":45118,
          "score":0,
          "version":0,
          "creator":{
            "type":1,
            "qq":259249381,
            "encrypt_uin":"ow4qowvqoic5",
            "name":"叶洛洛",
            "isVip":1,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3778321003",
          "createtime":"2018-03-21",
          "commit_time":"2018-03-21",
          "dissname":"冷门专区：陈红鲤的情绪收留所",
          "imgurl":"http://p.qpic.cn/music_cover/nTTGCyhtlCX09THicm2oy2UE3mmVastibXx7DREnSibYbia7VibiaDm96bJA/600?n=1",
          "introduction":"",
          "listennum":1861,
          "score":0,
          "version":0,
          "creator":{
            "type":1,
            "qq":1632018714,
            "encrypt_uin":"oKCiown5NeS57n**",
            "name":"陈红鲤",
            "isVip":1,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3787913001",
          "createtime":"2018-03-20",
          "commit_time":"2018-03-20",
          "dissname":"韩国地下嘻哈实力厂牌1LLIONAIRE",
          "imgurl":"http://p.qpic.cn/music_cover/icmord6PBGdDicuWKPmh9IGOM5B4uUjEbLlEIiaIiarXd4bK5HG3uGacpQ/600?n=1",
          "introduction":"",
          "listennum":35303,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":314541266,
            "encrypt_uin":"oi6P7Kv5owCs",
            "name":"褐",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3629174204",
          "createtime":"2018-01-02",
          "commit_time":"2018-01-02",
          "dissname":"心情唔好？食啖甜品，天都光晒！",
          "imgurl":"http://p.qpic.cn/music_cover/nGIvUJ7zJn2Dbb5IezsMbk12VFX1FoI7CibORlkMv7ibmee4sTKbrVfw/600?n=1",
          "introduction":"",
          "listennum":201367,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2765219558,
            "encrypt_uin":"owSs7K-5NK4kNn**",
            "name":"乌龙茶",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3631491546",
          "createtime":"2018-01-04",
          "commit_time":"2018-01-04",
          "dissname":"国内原创电子精选，冉冉升起的新星",
          "imgurl":"http://p.qpic.cn/music_cover/Q6jzKPNCPTc2iczypkicqzaJJicuyJ2Wq7HYXWAlicibzGHwGLS70qHcGXA/600?n=1",
          "introduction":"",
          "listennum":274619,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":775670247,
            "encrypt_uin":"7iSk7wSzowvl",
            "name":"杰少",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3264090856",
          "createtime":"2017-05-31",
          "commit_time":"2017-05-31",
          "dissname":"穿越云层：刺激神经传送体的极限运动",
          "imgurl":"http://p.qpic.cn/music_cover/iciaoSVS8WxkXbvAfpPWAcDQ8Z6DM680MFoJz4Ynazg5BiaTYzHqC9PGg/600?n=1",
          "introduction":"",
          "listennum":1084033,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2093612768,
            "encrypt_uin":"ownqoiC5owSsNn**",
            "name":"纯真，傻的可笑",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3609573278",
          "createtime":"2018-01-31",
          "commit_time":"2018-01-31",
          "dissname":"闺蜜日：适合促膝长谈的Piano Jazz",
          "imgurl":"http://p.qpic.cn/music_cover/llTQ9l2AeicK2OLIORnsUdqhLRIdrgcW2WcLLgjy7OibEbGZe8dBflzg/600?n=1",
          "introduction":"",
          "listennum":613285,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":348361207,
            "encrypt_uin":"oivFoiC5ownl",
            "name":"风少",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3771053884",
          "createtime":"2018-03-16",
          "commit_time":"2018-03-16",
          "dissname":"70首英文冷门remix",
          "imgurl":"http://p.qpic.cn/music_cover/PJrGzQib7nia43112ibFrSia1Lqm0RhFY4XAPGicvUkXjfsxa650icNapGow/600?n=1",
          "introduction":"",
          "listennum":228695,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":1545023735,
            "encrypt_uin":"oK4P7KnAoiSi7v**",
            "name":"Monster〃",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3776803226",
          "createtime":"2018-03-12",
          "commit_time":"2018-03-12",
          "dissname":"流觞曲水原创音乐团队古风作品",
          "imgurl":"http://p.qpic.cn/music_cover/4Ticib0ZqQSNiayibWKtJ0wyHMe4AIAS1VXJsqzkkCeyrOrXHqRyuaiaibAg/600?n=1",
          "introduction":"",
          "listennum":191999,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2990867470,
            "encrypt_uin":"owEqoecs7ivlon**",
            "name":"钰莞夭夭",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"892434700",
          "createtime":"2018-03-21",
          "commit_time":"2018-03-21",
          "dissname":"Fresh Trap：无法抽离的致暗氛围",
          "imgurl":"http://p.qpic.cn/music_cover/et4ebGznl9hpXgFichYgfPII3VNxNsq1L9DAEoxo1ic2RMgQ5U3qRVnA/600?n=1",
          "introduction":"",
          "listennum":105300,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":1538968620,
            "encrypt_uin":"oK4iNeEsNeCAon**",
            "name":"薛之谦",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"1475881874",
          "createtime":"2017-08-05",
          "commit_time":"2017-08-05",
          "dissname":"热血沸腾！周刊少年JUMP动画歌曲大合集",
          "imgurl":"http://p.qpic.cn/music_cover/ZUBQpASRAicibpY9a3gJPTedgHl9Wxjf3n5zghAW7mR5kxjR6e0sjtMA/600?n=1",
          "introduction":"",
          "listennum":2629617,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":3342379852,
            "encrypt_uin":"oioPowolNKckoc**",
            "name":"私はとても良いです",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3578221011",
          "createtime":"2017-08-25",
          "commit_time":"2017-08-25",
          "dissname":"听小众港乐应该知道的65支香港乐队",
          "imgurl":"http://p.qpic.cn/music_cover/vT1naPTJ8sYQQb8x2xMFWsE5GGsfXvzVld9hV9zCD67eNBB96icqT3Q/600?n=1",
          "introduction":"",
          "listennum":487557,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":3376919139,
            "encrypt_uin":"oiol7wE5NK6iNv**",
            "name":"中午不睡觉",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3780454787",
          "createtime":"2018-03-15",
          "commit_time":"2018-03-15",
          "dissname":"喝点什么？华语歌中的心情饮品",
          "imgurl":"http://p.qpic.cn/music_cover/CJ35Z2cnZA0kWwtIMrxsbhuggGbPTst0faUAeFy7ibybgOfH8jdS2Hw/600?n=1",
          "introduction":"",
          "listennum":209649,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":86010258,
            "encrypt_uin":"NeCzoKnA7Kc*",
            "name":"霜泧",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3779582197",
          "createtime":"2018-03-16",
          "commit_time":"2018-03-16",
          "dissname":"民谣对唱：文艺青年的柔声倾诉",
          "imgurl":"http://p.qpic.cn/music_cover/T0qpeJj1MpLkoxkZMuVVx6efRz1bfKh3Ps8GPWiaw1AFrVLufTIaO0w/600?n=1",
          "introduction":"",
          "listennum":788229,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":810360741,
            "encrypt_uin":"Ne6zoiCz7iv5",
            "name":"被嫌弃的唐唐的一生",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3748642387",
          "createtime":"2018-03-17",
          "commit_time":"2018-03-17",
          "dissname":"Christian Rock：摇滚青年的信仰",
          "imgurl":"http://p.qpic.cn/music_cover/llTQ9l2AeicK2OLIORnsUdqhLRIdrgcW2OjsBSzkwViaVIxEkEBiaIib8w/600?n=1",
          "introduction":"",
          "listennum":160589,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":348361207,
            "encrypt_uin":"oivFoiC5ownl",
            "name":"风少",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3643235781",
          "createtime":"2018-03-15",
          "commit_time":"2018-03-15",
          "dissname":"【迷幻trap】置身于迷离之境",
          "imgurl":"http://p.qpic.cn/music_cover/et4ebGznl9hpXgFichYgfPII3VNxNsq1LtlfmibAR7YxVGK8N6W4iah0w/600?n=1",
          "introduction":"",
          "listennum":185240,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":1538968620,
            "encrypt_uin":"oK4iNeEsNeCAon**",
            "name":"薛之谦",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3770704798",
          "createtime":"2018-03-10",
          "commit_time":"2018-03-10",
          "dissname":"获格莱美最多的艺术家单曲精选",
          "imgurl":"http://p.qpic.cn/music_cover/tmk5HNSnJvJhsOvcIpWulWdzRXicVoxE9IUPyKuog7t7wqDe01K6evw/600?n=1",
          "introduction":"",
          "listennum":45801,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":2958598324,
            "encrypt_uin":"owEkNe4qNeoA7n**",
            "name":"biG橘子",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3771344478",
          "createtime":"2018-03-13",
          "commit_time":"2018-03-13",
          "dissname":"2018年1-3月欧美电子新歌精选",
          "imgurl":"http://p.qpic.cn/music_cover/Kw0js0dh71gAUlYpdebialwxanIU7IR72sGNyrQGbscYFibKpmXAxp0A/600?n=1",
          "introduction":"",
          "listennum":279309,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":1738160012,
            "encrypt_uin":"oKSiNe6soen5oc**",
            "name":"木头",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3635728953",
          "createtime":"2018-01-29",
          "commit_time":"2018-01-29",
          "dissname":"蜜汁撩法 | 单身人士听了想谈恋爱",
          "imgurl":"http://p.qpic.cn/music_cover/aaxX4Babic4VicBPicJOwr5xia5xibicWzHDVld5f2B2IH1DSjE7kfmjAf9A/600?n=1",
          "introduction":"",
          "listennum":246537,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":1600189472,
            "encrypt_uin":"oKCzoe6FNKvloc**",
            "name":"默笙",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"1781021825",
          "createtime":"2017-09-29",
          "commit_time":"2017-09-29",
          "dissname":"每科都考99分！学霸专用的唯美の纯音",
          "imgurl":"http://p.qpic.cn/music_cover/qH8rLHHhL8O8Iibm56uPzJ9ia5TwehMggWBgdVGN2sEgxcfHJmswtib5w/600?n=1",
          "introduction":"",
          "listennum":8806338,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":1812948313,
            "encrypt_uin":"oKc5owEPNeo5oz**",
            "name":" 私に闻いて风i",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3777695111",
          "createtime":"2018-03-16",
          "commit_time":"2018-03-16",
          "dissname":"未来可期∶20位00后原创歌手的音乐梦",
          "imgurl":"http://p.qpic.cn/music_cover/jF1CHiathfGvgNZrwbCZkzm9SuUCEhMbgILcvK1RFxZ6EDYPut0VNqA/600?n=1",
          "introduction":"",
          "listennum":179477,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":1759591760,
            "encrypt_uin":"oKSkNK4qoKSson**",
            "name":"落兮",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3788372609",
          "createtime":"2018-03-20",
          "commit_time":"2018-03-20",
          "dissname":"SPINNIN:2006-2018作品全收录",
          "imgurl":"http://p.qpic.cn/music_cover/PiajxSqBRaEJPtLXYsvILNeibhQQ90hYp5J3bmwUQibUtwhTOLF5riaTEg/600?n=1",
          "introduction":"",
          "listennum":32125,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":4960643,
            "encrypt_uin":"7eEsoeCPoz**",
            "name":"black",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3758085323",
          "createtime":"2018-03-16",
          "commit_time":"2018-03-16",
          "dissname":"日系女声：甜度100%的动漫主题曲",
          "imgurl":"http://p.qpic.cn/music_cover/4SToLgyAFibJLOGopcPDpxqNhXX55VzuN1IKdwH40DEuSnESFd76vpg/600?n=1",
          "introduction":"",
          "listennum":113839,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":1978787848,
            "encrypt_uin":"oKElNeSF7icPNn**",
            "name":"Extraordinary",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3699672719",
          "createtime":"2018-01-29",
          "commit_time":"2018-01-29",
          "dissname":"在战火硝烟中诞生的古典音乐",
          "imgurl":"http://p.qpic.cn/music_cover/3gNibArB0BKquGve7mp3bdliaF8SVkUTaAXceOaZkmTKY7KLDWXHcPvw/600?n=1",
          "introduction":"",
          "listennum":29848,
          "score":0,
          "version":0,
          "creator":{
            "type":0,
            "qq":2083172477,
            "encrypt_uin":"ownFoi6lowvl7z**",
            "name":"焦糖玛奇朵",
            "isVip":0,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3786939902",
          "createtime":"2018-03-19",
          "commit_time":"2018-03-19",
          "dissname":"韩国90后女歌手精选",
          "imgurl":"http://p.qpic.cn/music_cover/ibJJngZRP5m8ksRvDkGZxdd5B4ibYQra3ibknF8pt8O8jqKp9wVSsNxgA/600?n=1",
          "introduction":"",
          "listennum":123887,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":793407810,
            "encrypt_uin":"7iEi7enlNe6z",
            "name":"谈谈心恋恋爱 *",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        },
        {
          "dissid":"3654610479",
          "createtime":"2018-01-15",
          "commit_time":"2018-01-15",
          "dissname":"认哥Alphago｜金希澈的劲歌金曲",
          "imgurl":"http://p.qpic.cn/music_cover/icLTHicH8iakBFAJbiazGT3Dn1MdbKyzzOPcP9UAAyiaTr83D8UFOESrl7w/600?n=1",
          "introduction":"",
          "listennum":49766,
          "score":0,
          "version":0,
          "creator":{
            "type":2,
            "qq":631851806,
            "encrypt_uin":"7wo5Ne45Nens",
            "name":"虛榮少女",
            "isVip":2,
            "avatarUrl":"",
            "followflag":0
          }
        }
      ]
    }
  }
}